In [3]:
import numpy as np


In [6]:
x = np.array([[1.0,0.5],[0.3,0.8]])
W1 = np.array([[0.2,0.3],[0.3,0.4]])
b1 = np.array([0.2,0.4])
A1 = np.dot(x,W1)+b1
A1

array([[0.55, 0.9 ],
       [0.5 , 0.81]])

In [14]:
def sigmoid(x):
    return x

In [15]:
Z1 = sigmoid(A1)
Z1

array([[0.55, 0.9 ],
       [0.5 , 0.81]])

In [16]:
Z1.shape

(2, 2)

In [18]:
W2 = np.array([0.5,0.8])
b2 = np.array([0.2,0.1])
A2 = np.dot(Z1,W2)+b2
A2

array([1.195, 0.998])

In [19]:
Z2 = sigmoid(A2)
Z2

array([1.195, 0.998])

In [20]:
Z2.shape

(2,)

In [27]:
def identity_function(x):
    return x

In [28]:
W3 = np.array([[0.2,0.9],[0.9,0.4]])
b3 = np.array([0.2,0.3])
A3 = np.dot(Z2,W3)+b3
A3

array([1.3372, 1.7747])

In [29]:
Y = identity_function(A3)
Y

array([1.3372, 1.7747])

In [30]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.2,0.4,0.5],[0.1,0.4,0.3]])
    network['b1'] = np.array([0.5,0.9,0.2])
    network['W2'] = np.array([[0.1,0.8,0.9],[0.2,0.5,0.4]])
    network['b2'] = np.array([0.1,0.3,0.2])
    network['W3'] = np.array([[0.1,0.2,0.9],[0.9,0.2,0.3]])
    network['b3'] = np.array([0.2,0.9,0.1])
    return network

In [33]:
def forward(network,x):
    W1,W2,W3 = network['W1'],network['W2'],network['W3']
    b1,b2,b3 = network['b1'],network['b2'],network['b3']
    

    

In [34]:
a1 = np.dot(x,W1)+b1
z1 = sigmoid(a1)
a2 = np.dot(z1,W2)+b2
z2 = sigmoid(a2)
a3 = np.dot(z2,W3)+b3
z3 = sigmoid(a3)
y = identity_function(a3)
    
    return y


SyntaxError: 'return' outside function (2315836097.py, line 9)

In [35]:
network = init_network()
x = np.array([1.0,0.5])
y = forward(network,x)
y