In [1]:
# 기초 tensorflow api

In [2]:
import tensorflow as tf

In [4]:
# python은 상수(constant) 개념이 없습니다. 모든 것이 변경 가능합니다.
# 상수는 한 번 정의되면 값을 변경할 수 없습니다.
a = tf.constant(1) #상수 정의

In [5]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [6]:
a = tf.constant([[1, 2, 3], [4, 5, 6]])

In [7]:
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [6]:
# 상수의 값을 가져옵니다
a.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# 텐서는 넘파이의 ndarray와 마찬가지로 슬라이싱,
# 切片, 索引.슬라이싱, 인덱싱.
a[0] # 첫 번째 행 가져오기

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [9]:
# 索引 인덱싱
a[1, 1].numpy() # 값을 가져올 때 항상 numpy()를 추가해야합니다.

5

In [10]:
a[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]])>

In [11]:
# TensorFlow에는 고유한 슬라이스 작성 방법이 있습니다
# ...은 쉼표 이전의 모든 차원을 나타냅니다.
# a가 3 차원 인 경우 a [:, :, 1:]
a[..., 1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]])>

In [12]:
# 상수의 작업
# 주의: 상수를 수정하지 않고 새로운 텐서를 반환합니다.
a + 1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7]])>

In [14]:
# 用新的tensor把a覆盖掉了.
a = tf.square(a)

In [15]:
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]])>

In [16]:
# 如果对常量进行assign,那么就会报错, 但是因为a是常量, 没有assign方法.
a.assign()

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [20]:
# 直接修改常量内部的值. 会报错.
a[0, 1] = 20

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [21]:
# tensor와 ndarray의 변환
# 텐서를 ndarray로 변환했습니다.
a.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
import numpy as np

In [23]:
b = np.random.randint(0, 10, size=(3, 4))

In [24]:
b

array([[0, 9, 9, 7],
       [3, 8, 9, 2],
       [9, 6, 6, 4]])

In [25]:
# tensor를 ndarray로 변환하려면, ndarray를 직접 사용하여 tensor를 만듭니다.
tf.constant(b)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 9, 9, 7],
       [3, 8, 9, 2],
       [9, 6, 6, 4]])>

In [ ]:
# vector/matrix
# 하나의 숫자, 대괄호 없이 표시된 것을 스칼라(scalar)라고합니다.

In [26]:
# a는 스칼라입니다.
a = tf.constant(1)

In [27]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [32]:
# 스칼라가 아닙니다.
b = tf.constant([[1, 2, 3], [2, 3, 4]])

In [29]:
a.shape

TensorShape([])

In [33]:
b.shape

TensorShape([2, 3])

In [34]:
a = tf.constant('abcd')

In [35]:
print(a)

tf.Tensor(b'abcd', shape=(), dtype=string)


In [36]:
# 문자열 메소드
# 문자열의 길이 계산
tf.strings.length(a)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [38]:
# utf8의 인코딩 길이
tf.strings.length(a, unit='UTF8_CHAR')

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [42]:
# 문자열 인코딩 방식 변환
tf.strings.unicode_encode(tf.strings.unicode_decode(a, 'UTF8'), 'UTF-8')

<tf.Tensor: shape=(), dtype=string, numpy=b'abcd'>

In [43]:
# 문자열 배열
t = tf.constant(['cafe', 'coffee', '咖啡'])
t

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'cafe', b'coffee', b'\xe5\x92\x96\xe5\x95\xa1'], dtype=object)>

In [46]:
tf.strings.length(t, unit='UTF8_CHAR')

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 6, 2])>

In [47]:
tf.strings.unicode_decode(t, 'UTF8')

<tf.RaggedTensor [[99, 97, 102, 101], [99, 111, 102, 102, 101, 101], [21654, 21857]]>

In [50]:
# ragged tensor는 규칙적이지 않은 텐서를 의미합니다.
r = tf.ragged.constant([[11, 12], [1, 2, 3], [], [0]])


In [49]:
tf.constant([[11, 12], [1, 2, 3], [], [0]])
# 비정형 Python 시퀀스를 tensor로 변환할 수 없기 때문에 오류가 발생합니다.


ValueError: Can't convert non-rectangular Python sequence to Tensor.

In [51]:
r[1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [53]:
# 左闭右开的切片./왼쪽은 포함하고, 오른쪽은 제외하는 슬라이싱.
r[1:3]

<tf.RaggedTensor [[1, 2, 3], []]>

In [54]:
# ndarray는 결합할 수 있습니다
r

<tf.RaggedTensor [[11, 12], [1, 2, 3], [], [0]]>

In [55]:
r2 = tf.ragged.constant([[10, 11], [4, 5, 6], [], [1]])

In [58]:
# 축 = 1은 열에 대한 작업입니다. 열 수가 증가합니다.
tf.concat([r, r2], axis=1)

<tf.RaggedTensor [[11, 12, 10, 11], [1, 2, 3, 4, 5, 6], [], [0, 1]]>

In [59]:
# 축 = 0은 행에 대한 작업입니다. 행 수가 증가합니다.
tf.concat([r, r2], axis=0)

<tf.RaggedTensor [[11, 12], [1, 2, 3], [], [0], [10, 11], [4, 5, 6], [], [1]]>

In [60]:
r3 = tf.ragged.constant([[1, 2], [], [11]])

In [61]:
tf.concat([r, r3], axis=0)

<tf.RaggedTensor [[11, 12], [1, 2, 3], [], [0], [1, 2], [], [11]]>

In [62]:
tf.concat([r, r3], axis=1)
# 결합 작업을 수행할 때 두 텐서의 모양은 결합 축에서 동일한 길이를 가져야  합니다
# 그래서 오류가 발생합니다

InvalidArgumentError: Input tensors have incompatible shapes.
Condition x == y did not hold.
First 1 elements of x:
[3]
First 1 elements of y:
[4]