In [1]:

import torch

In [2]:
torch.__version__

'2.0.0'

In [3]:

torch.cuda.is_available()

True

In [4]:
# GPU
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 3050 Ti Laptop GPU'

### pytorch张量

In [5]:
torch.tensor([1, 2, 3, 4], dtype=torch.float32)

tensor([1., 2., 3., 4.])

In [8]:
import tensorflow as tf

In [9]:
# tensorflow 中没有tensor方法来直接创建tensor, tensorflow中创建tensor都是通过constant, Variable
# pytorch中没有常量变量的说法, 统一都是变量. 
tf.tensor([1, 2, 3, 4], dtype=tf.float32)

AttributeError: module 'tensorflow' has no attribute 'tensor'

In [10]:
import numpy as np

In [11]:
# 也可以通过ndarray来创建tensor
torch.tensor(np.array([1, 2, 3, 4]), dtype=torch.float32)

tensor([1., 2., 3., 4.])

In [12]:
torch.tensor(np.array([1, 2, 3, 4]))

tensor([1, 2, 3, 4], dtype=torch.int32)

In [13]:
# numpy 中有一些routines函数(常规函数), 可以让我们快速的创建ndarray.
# torch中也有这样的函数, 连名字都差不多, 功能是一样的. 
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
torch.ones(*(3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
torch.eye(8)

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.full((3, 4), fill_value=8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [21]:
torch.full((3, 4), 8)

tensor([[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]])

In [22]:
np.linspace(0, 100, )

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [23]:
torch.linspace(0, 100, 50)

tensor([  0.0000,   2.0408,   4.0816,   6.1224,   8.1633,  10.2041,  12.2449,
         14.2857,  16.3265,  18.3673,  20.4082,  22.4490,  24.4898,  26.5306,
         28.5714,  30.6122,  32.6531,  34.6939,  36.7347,  38.7755,  40.8163,
         42.8571,  44.8980,  46.9388,  48.9796,  51.0204,  53.0612,  55.1020,
         57.1429,  59.1837,  61.2245,  63.2653,  65.3061,  67.3469,  69.3878,
         71.4286,  73.4694,  75.5102,  77.5510,  79.5918,  81.6327,  83.6735,
         85.7143,  87.7551,  89.7959,  91.8367,  93.8775,  95.9184,  97.9592,
        100.0000])

In [24]:
np.random.normal(loc=10, scale=3, size=(5, 6))

array([[ 7.57078942,  7.62640896, 13.26774293,  2.86481841, 11.83263521,
        12.34075489],
       [ 8.49821798,  9.21910608,  6.3984334 , 13.62876322, 16.46467508,
        11.8140126 ],
       [ 9.26063068,  7.17044959,  8.10019884, 12.4162967 , 14.91681618,
         8.39253031],
       [13.48390163, 13.04434526,  7.32414995,  0.02470767, 10.64433855,
         7.99346332],
       [13.43322513, 13.08431756, 11.39862531, 12.09430618,  3.85741263,
        14.5198482 ]])

In [43]:
# 토치(tensor)에서는 랜덤(random)을 사용하지 않고, 임의의 수를 생성할 수 있습니다
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([ 0.8477,  1.6020,  3.5086,  3.5197,  4.1114,  5.6580,  6.9891,  7.5659,
         8.6576, 10.1114])

In [26]:
# 표준 정규 분포 (Standard Normal Distribution)
torch.randn(4, 5)

tensor([[ 0.2856,  0.1230,  0.7389,  1.2756,  0.6001],
        [-1.0147, -0.3550, -1.2774, -0.9994,  1.8197],
        [-0.3327, -1.1594, -0.0996,  0.4943,  0.1348],
        [-0.5838, -0.5642,  0.7396,  0.8806, -0.2443]])

In [27]:
# 0에서 1 사이의 임의의 수 (0부터 1까지의 무작위 수)
torch.rand(2, 3)

tensor([[0.0410, 0.2836, 0.7346],
        [0.8655, 0.8262, 0.1303]])

In [28]:
t = torch.randint(0, 10, size=(4, 5))
t

tensor([[5, 8, 0, 8, 6],
        [7, 0, 0, 2, 6],
        [1, 8, 1, 1, 6],
        [2, 7, 7, 6, 6]])

In [29]:
n = np.random.randint(0, 10, size=(4, 5))
n

array([[8, 5, 8, 8, 2],
       [6, 6, 9, 5, 3],
       [5, 0, 3, 8, 3],
       [3, 2, 1, 9, 1]])

In [30]:
# ndarray : ndim, shape, size, dtype
# 텐서(tensor)는 기본적으로 같지만, 요소의 총 개수가 없고, size() 메서드가 추가되었습니다.
t.ndim

2

In [31]:
t.shape

torch.Size([4, 5])

In [32]:
# size()와 .shape은 모두 형태(shape)를 나타내는 것으로 동일합니다. 
t.size()

torch.Size([4, 5])

In [33]:
t.dtype

torch.int64

In [34]:
t.size(1)

5

### 텐서(tensor)의 데이터 타입(dtype)

In [35]:
torch.float32 32位浮点数
torch.float64
toch.int32
torch.int16
torch.int64
torch.long 这个经常在pytorch中用来做target的数据类型. 

SyntaxError: invalid syntax (113207785.py, line 1)

In [36]:
# 텐서(tensor)를 생성할 때 dtype을 지정하여 데이터 타입을 설정할 수 있습니다.
t1 = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
t2 = torch.tensor([1, 2, 3, 4], dtype=torch.long)

In [37]:
t1

tensor([1., 2., 3., 4.])

In [38]:
t2

tensor([1, 2, 3, 4])

In [39]:
torch.long

torch.int64

In [40]:
t1 + t2

tensor([2., 4., 6., 8.])

### 텐서 연산

In [41]:
t1 + 1

tensor([2., 3., 4., 5.])

In [57]:
# 동일한 형태를 가지는 텐서의 대응하는 위치의 요소를 계산하기 위해서는 PyTorch 라이브러리의 다양한 함수와 연산자를 사용할 수 있습니다.
t1 + t2

tensor([2., 4., 6., 8.])

In [58]:
# 형태가 다를 경우 PyTorch에는 브로드캐스팅(broadcasting) 메커니즘이 있습니다.
# 1. 차원 부족 시 차원을 추가합니다.
# 2. 데이터가 부족한 경우, 기존의 유일한 데이터를 사용하여 데이터를 보충합니다.
a = np.arange(4).reshape(4, 1)
a

array([[0],
       [1],
       [2],
       [3]])

In [59]:
b = np.arange(4)
b


array([0, 1, 2, 3])

In [60]:
a + b

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [63]:
c = np.array([[0, 1, 2, 3], [0, 1, 2, 3]])
c

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [65]:
a + c

ValueError: operands could not be broadcast together with shapes (4,1) (2,4) 

In [66]:
b + c

array([[0, 2, 4, 6],
       [0, 2, 4, 6]])

In [67]:
ta = torch.tensor(a)
tb = torch.tensor(b)

In [68]:
ta, tb

(tensor([[0],
         [1],
         [2],
         [3]], dtype=torch.int32),
 tensor([0, 1, 2, 3], dtype=torch.int32))

In [69]:
# PyTorch에는 NumPy와 유사한 브로드캐스팅(broadcasting) 메커니즘이 있습니다
ta + tb

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6]], dtype=torch.int32)

In [71]:
t_a = tf.constant(a)
t_b = tf.constant(b)
t_a + t_b

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])>

In [75]:

ta.add(tb) 
ta.subtract(tb)

ta.multiply(tb)
ta.divide(tb)

tensor([[   nan, 0.0000, 0.0000, 0.0000],
        [   inf, 1.0000, 0.5000, 0.3333],
        [   inf, 2.0000, 1.0000, 0.6667],
        [   inf, 3.0000, 1.5000, 1.0000]])

In [77]:
a.reshape(1, 4) @ b

array([14])

In [78]:
ta.reshape(1, 4) @ tb

tensor([14], dtype=torch.int32)

In [79]:
# matrix multiply
ta.reshape(1, 4).matmul(tb)

tensor([14], dtype=torch.int32)

In [80]:
# PyTorch에는 원본 데이터를 수정할 수 있는 특수한 메서드들이 있습니다. 이러한 메서드들은 밑줄(_)로 끝나는 형태를 가지고 있습니다.
ta.add(1)

tensor([[1],
        [2],
        [3],
        [4]], dtype=torch.int32)

In [82]:
# PyTorch의 모든 밑줄(_)로 끝나는 함수는 원본 데이터를 직접 수정하는 기능을 가지고 있습니다.
ta.add_(1)

tensor([[1],
        [2],
        [3],
        [4]], dtype=torch.int32)

In [83]:
ta

tensor([[1],
        [2],
        [3],
        [4]], dtype=torch.int32)

In [ ]:
# tensor的索引, 切片, 变形. 和numpy完全一样. 

In [84]:
# tensor的索引: 和numpy完全一样. 
t = torch.randint(0, 10, size=(4, 5))
t

tensor([[0, 3, 2, 6, 6],
        [8, 0, 7, 3, 7],
        [4, 6, 5, 8, 6],
        [7, 7, 4, 9, 8]])

In [85]:
t[0, 0]

tensor(0)

In [86]:
t[0]

tensor([0, 3, 2, 6, 6])

In [87]:
# 左闭右开
t[1:3]

tensor([[8, 0, 7, 3, 7],
        [4, 6, 5, 8, 6]])

In [88]:
t[:, 1:3]

tensor([[3, 2],
        [0, 7],
        [6, 5],
        [7, 4]])

In [89]:
t[1:3, 1:3]

tensor([[0, 7],
        [6, 5]])

In [90]:
t.shape

torch.Size([4, 5])

In [91]:
t.reshape(4, 5, 1)

tensor([[[0],
         [3],
         [2],
         [6],
         [6]],

        [[8],
         [0],
         [7],
         [3],
         [7]],

        [[4],
         [6],
         [5],
         [8],
         [6]],

        [[7],
         [7],
         [4],
         [9],
         [8]]])

In [92]:
# 最后一个维度, None表示占个位置, 
t[:, :, None]

tensor([[[0],
         [3],
         [2],
         [6],
         [6]],

        [[8],
         [0],
         [7],
         [3],
         [7]],

        [[4],
         [6],
         [5],
         [8],
         [6]],

        [[7],
         [7],
         [4],
         [9],
         [8]]])

In [93]:
# ...表示前面所有的维度. 
t[..., None]

tensor([[[0],
         [3],
         [2],
         [6],
         [6]],

        [[8],
         [0],
         [7],
         [3],
         [7]],

        [[4],
         [6],
         [5],
         [8],
         [6]],

        [[7],
         [7],
         [4],
         [9],
         [8]]])

In [98]:
# 中间的维度也能挤. 
t[:, None, :].squeeze().shape

torch.Size([4, 5])

In [97]:
# 把没有数据的维度挤压掉. 
t.reshape(4, 5, 1).squeeze().shape

torch.Size([4, 5])

In [103]:
# unsqueeze跟squeeze相反. 
t.unsqueeze(dim=1).shape

torch.Size([4, 1, 5])

In [ ]:
t.expand()

In [104]:
x = torch.tensor([[1], [2], [3]])
x.shape

torch.Size([3, 1])

In [106]:
# 跟广播机制一样, 只能用唯一的数据去扩充. 
x.expand(5, 4)

RuntimeError: The expanded size of the tensor (5) must match the existing size (3) at non-singleton dimension 0.  Target sizes: [5, 4].  Tensor sizes: [3, 1]

In [107]:
# batch_size, W, H, C
n = np.random.random((32, 224, 224, 3))
n.shape

(32, 224, 224, 3)

In [108]:
n[0, :, :, 0].shape

(224, 224)

In [109]:
t = torch.tensor(n)
t.shape

torch.Size([32, 224, 224, 3])

In [110]:
t[0, :, :, 0].shape

torch.Size([224, 224])

In [ ]:
# tensor变形也是用reshape
# view 也是变形的意思. 

In [111]:
t = torch.randint(0, 10, size=(4, 5))
t

tensor([[4, 7, 5, 6, 3],
        [7, 6, 7, 3, 7],
        [4, 2, 4, 6, 5],
        [8, 9, 5, 2, 6]])

In [112]:
t.reshape(5, 4)

tensor([[4, 7, 5, 6],
        [3, 7, 6, 7],
        [3, 7, 4, 2],
        [4, 6, 5, 8],
        [9, 5, 2, 6]])

In [113]:
t.view(5, 4)

tensor([[4, 7, 5, 6],
        [3, 7, 6, 7],
        [3, 7, 4, 2],
        [4, 6, 5, 8],
        [9, 5, 2, 6]])

In [ ]:
view和reshape是一样的吗?
# view对连续存储的数据进行reshape
# reshape没限制. 

In [ ]:
网上那种numpy 100题拿来练有用吗? 
非常有用, 赶紧去练. 
# numpy pandas matplotlib, seaborn

In [114]:
# 聚合运算
# pytorch聚合的时候不指定维度和numpy表现是一样的, 会把所有的维度聚合成一个数字. 
t.sum()

tensor(106)

In [118]:
# pytorch中维度不叫axis, dim dimension
# keepdim保持被聚合掉的维度继续存在. 
t.sum(dim=1, keepdim=True).shape # 4, 5

torch.Size([4, 1])

In [ ]:
# max min, mean, median, sum, argmin, argmax, std

In [120]:
t

tensor([[4, 7, 5, 6, 3],
        [7, 6, 7, 3, 7],
        [4, 2, 4, 6, 5],
        [8, 9, 5, 2, 6]])

In [119]:
t.argmax(dim=1)

tensor([1, 0, 3, 1])

In [121]:
# tensor的拼接
t1 = torch.randint(0, 10, size=(4, 5))
t1

tensor([[0, 4, 1, 3, 6],
        [4, 0, 0, 1, 9],
        [6, 5, 8, 3, 3],
        [4, 1, 3, 3, 4]])

In [122]:
t2 = torch.randint(0, 10, size=(4, 5))
t2

tensor([[2, 7, 9, 7, 7],
        [2, 4, 2, 6, 7],
        [0, 5, 5, 1, 2],
        [6, 5, 3, 9, 6]])

In [124]:
# pytorch也有dot, 但是, 仅限于向量之间的运算. 
# 一维向量的点乘. 
t1[0].dot(t2[0])

tensor(100)

In [125]:
# concatenate
# 默认也是按照axis=0, 即dim=0
torch.concat((t1, t2))

tensor([[0, 4, 1, 3, 6],
        [4, 0, 0, 1, 9],
        [6, 5, 8, 3, 3],
        [4, 1, 3, 3, 4],
        [2, 7, 9, 7, 7],
        [2, 4, 2, 6, 7],
        [0, 5, 5, 1, 2],
        [6, 5, 3, 9, 6]])

In [126]:
torch.concat((t1, t2), dim=1)

tensor([[0, 4, 1, 3, 6, 2, 7, 9, 7, 7],
        [4, 0, 0, 1, 9, 2, 4, 2, 6, 7],
        [6, 5, 8, 3, 3, 0, 5, 5, 1, 2],
        [4, 1, 3, 3, 4, 6, 5, 3, 9, 6]])

In [127]:
# 水平拼接
torch.hstack((t1, t2))

tensor([[0, 4, 1, 3, 6, 2, 7, 9, 7, 7],
        [4, 0, 0, 1, 9, 2, 4, 2, 6, 7],
        [6, 5, 8, 3, 3, 0, 5, 5, 1, 2],
        [4, 1, 3, 3, 4, 6, 5, 3, 9, 6]])

In [128]:
torch.vstack((t1, t2))

tensor([[0, 4, 1, 3, 6],
        [4, 0, 0, 1, 9],
        [6, 5, 8, 3, 3],
        [4, 1, 3, 3, 4],
        [2, 7, 9, 7, 7],
        [2, 4, 2, 6, 7],
        [0, 5, 5, 1, 2],
        [6, 5, 3, 9, 6]])

In [129]:
t3 = torch.randint(0, 10, size=(5, 6))
t3

tensor([[4, 7, 9, 1, 6, 1],
        [1, 0, 1, 5, 6, 6],
        [1, 9, 4, 8, 2, 6],
        [8, 4, 5, 1, 8, 1],
        [8, 0, 2, 6, 9, 5]])

In [130]:
torch.hstack((t1, t3))

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 4 but got size 5 for tensor number 1 in the list.

In [131]:
torch.vstack((t1, t3))

RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 5 but got size 6 for tensor number 1 in the list.

In [132]:
t.shape

torch.Size([4, 5])

In [138]:
t.split([1, 2, 1])

(tensor([[4, 7, 5, 6, 3]]),
 tensor([[7, 6, 7, 3, 7],
         [4, 2, 4, 6, 5]]),
 tensor([[8, 9, 5, 2, 6]]))

In [134]:
t

tensor([[4, 7, 5, 6, 3],
        [7, 6, 7, 3, 7],
        [4, 2, 4, 6, 5],
        [8, 9, 5, 2, 6]])

In [139]:
import glob

In [143]:
glob.glob('./*.ipynb')

['.\\pytorch入门.ipynb']

In [162]:
np.random.permutation([0, 1, 2, 3])

array([2, 0, 1, 3])

In [163]:
t.shape

torch.Size([4, 5])

In [164]:
# 就是转置, 就是transpose
torch.permute(t, [1, 0]).shape

torch.Size([5, 4])

In [165]:
t.transpose(1, 0).shape

torch.Size([5, 4])

### 张量的自动微分

In [2]:
# 自动微分其实就是求导. pytorch帮我们求导. 
# requires_grad=True表示要跟踪x的梯度即导数
x = torch.ones(2, 2, requires_grad=True)

y = 2 * x + 2

In [167]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [168]:
y

tensor([[4., 4.],
        [4., 4.]], grad_fn=<AddBackward0>)

In [169]:
# 求导一定要求是从标量开始. 标量就是一个数字. 
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [171]:
y.grad_fn

In [172]:
z = y.mean()

In [173]:
z

tensor(4., grad_fn=<MeanBackward0>)

In [174]:
z.backward()

In [175]:

# y = 2x + 2, y对x的导数是2, x有4个值, 平均, 一下, 每个值的导数就是2/ 4=0.5
x.grad

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

In [176]:
y.grad

D:\.venv\lib\site-packages\torch\_tensor.py:1104: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:475.)
  return self._grad


In [177]:
y.retain_grad()

In [3]:
z = y * y * 3
out = z.mean()

In [4]:
out.backward()

In [5]:
x.grad

tensor([[12., 12.],
        [12., 12.]])

In [10]:
# pytorch的版本发生了变化, 现在这个pytorch版本获取不到非叶子节点的导数了. 
y.retain_grad()

In [11]:
(x ** 2).requires_grad

True

In [12]:
# 如果不需要求导. 可以torch.no_grad()上下文来进行计算. 
# 经常用在预测的时候. 
with torch.no_grad():
    # 在with语句块中的任何计算, 都不会进行求导. 
    print((x ** 2).requires_grad)

False


In [13]:
# detach
y = x ** 2 + 2
# 因为x可以求导, 那么y自然也可以求导. 
y.requires_grad

True

In [15]:
# 返回的tensor其实就是y的值, 这个新的tensor是不能求导的, 因为detach掉了. 
# 相当于拷贝了一份y的值, 并且对这个值不求导. 
z = y.detach()

In [16]:
z.requires_grad

False

In [17]:
y.requires_grad

True

In [18]:
# 默认一个tensor是不能求导. 
t = torch.randn(3, 3)
t.requires_grad

False

In [19]:
# 可以通过requires_grad_() 修改requires_grad属性
t.requires_grad_(True)

tensor([[ 1.4985,  1.2438, -0.9422],
        [-0.3971,  0.1725, -1.4228],
        [-0.1768, -0.2805,  1.0932]], requires_grad=True)

In [20]:
t.requires_grad

True